### ISSUE TITLE
很多jar包下不下来

### ISSUE THREAD

**Issue by allenyuzhenlong** [a466350665/smart#4]
很多jar包下不下来

**Comment by a466350665** [comment]
maven有配置好吗  http://blog.csdn.net/a466350665/article/details/48573501

**Comment by allenyuzhenlong** [comment]
@a466350665 是的，配置好了，除了仓库位置其他设置都跟你博客的一样，但是有些能下，有些需要换个版本才能下下来，但是每个jar都去修改版本要花很多时间，所以才想着问下你，看下下不下来是什么原因。
![image](https://cloud.githubusercontent.com/assets/15882327/20783135/c5a355d4-b7cc-11e6-87c3-6a807d03d449.png)

**Comment by a466350665** [comment]
有没有指定特定的maven镜像地址，smart都是用的较新版本的jar，有可能指定的镜像没有这些新版本。还有网络问题也可能导致jar包下载不成功，这种情况可以删掉repository目录中对应的jar重新下载试试

**Comment by allenyuzhenlong** [comment]
@a466350665 嗯，我清理下，全部重新下载看看，下载速度确实很慢。另外我问下，这个SSO是基于什么框架做的呢？cas吗？这个SSO支持移动端吗？因为移动端是没有cookie的。

**Comment by a466350665** [comment]
sso是参考的cas原理，笔者的代码实现，在安全上还在进一步改造更新，移动端需要每次的请求都传递登录的token参数，来保持会话就好，请求也最好的https协议，防止截取信息

**Comment by allenyuzhenlong** [comment]
我把maven 配了个阿里云仓库的镜像，快多了，默认从外国下实在太慢了。另外貌似这个项目暂时没有集成Oauth哈？

**Comment by allenyuzhenlong** [comment]
@a466350665 你好!我问下smart-mvc-mybatis-demo这个tomcat实例为什么迟迟不能启动成功？也不报错，直到超过了tomcat设置的timeout，才报时间到了还没启动成功的错。

**Comment by allenyuzhenlong** [comment]
@a466350665 2016-12-01 17:05:18,104 DEBUG o.s.beans.factory.support.DefaultListableBeanFactory - Returning cached instance of singleton bean 'authenticationRpcService' 好像一直等这个RPC的实例，但是一直没返回，你没碰到过吗？

**Comment by a466350665** [comment]
可以看一下文档《单点登录权限系统-部署.docx》，需要先启动smart-sso-server实例再启动smart-mvc-mybatis-demo，因为demo系统的权限是通过RPC去smart-sso-server拿的

**Comment by allenyuzhenlong** [comment]
@a466350665 解决了，是因为文档说明中两个tomcat端口是80和8080，而代码里面是8080和8081，所以迟迟启动不了

**Comment by a466350665** [comment]
好的，文档是早期写的，部署的是80和8080，这几天会更新好，欢迎多给建议！

**Comment by dingxh317** [comment]
你好，项目能起来但是一登录的时候页面总是报错
org.apache.ibatis.binding.BindingException: Invalid bound statement (not found): com.smart.sso.server.dao.UserDao.findByAccount
请问这是什么原因啊？

**Comment by a466350665** [comment]
检查一下jdbc.properties配置，看是不是数据库没连上?

**Comment by Blucezhang** [comment]
这个
org.apache.ibatis.binding.BindingException: Invalid bound statement (not found): com.smart.sso.server.dao.UserDao.findByAccounts，问题怎么回事，各种原因排查过了，就是不行啊，jdbc.properties连上了

**Comment by a466350665** [comment]
怎么findByAccounts方法会多个s

**Comment by waitinguhere** [comment]
你好，文档在哪里？

**Comment by a466350665** [comment]
文档有更新，刚上传了
![image](https://cloud.githubusercontent.com/assets/19278040/22968945/84011a5a-f3a7-11e6-8c86-396083184301.png)

**Comment by waitinguhere** [comment]
你好，启动sso-server报错如下，请问这是哪里配置有问题？
![or6 ket s8_dwl1vg](https://cloud.githubusercontent.com/assets/25574037/23243272/be0e83f6-f9b8-11e6-8cae-c55d70316b39.png)

**Comment by a466350665** [comment]
mysql密码是否正确
![image](https://cloud.githubusercontent.com/assets/19278040/23243441/fa30c42e-f9b9-11e6-944a-630cdcf60b02.png)

**Comment by waitinguhere** [comment]
已经修改了，密码是正确的。我用mysql客户端都可以连接上

**Comment by waitinguhere** [comment]
![y_top0u ww77 22dk m6dp](https://cloud.githubusercontent.com/assets/25574037/23243699/9b35bf40-f9bb-11e6-9b01-aab1064ab52c.png)
![yue n5 x h4qa3w j4](https://cloud.githubusercontent.com/assets/25574037/23243705/a5762f26-f9bb-11e6-9bff-9bdd2cbd68ec.png)

**Comment by a466350665** [comment]
先去吃饭  下午帮你详细看下

**Comment by waitinguhere** [comment]
好的，没想到你那么快就回复了。麻烦你了，谢谢。

**Comment by a466350665** [comment]
你容器是用的tomcat还是jetty，看一下smart-sso-server的编译目录下有没有对应的Mapper文件
![image](https://cloud.githubusercontent.com/assets/19278040/23245926/2a7b31ee-f9cb-11e6-833d-f136d17c04a3.png)

**Comment by waitinguhere** [comment]
Tomcat，还真没发现这个文件夹。

**Comment by waitinguhere** [comment]
![5 1 s bk5p4 6 5w 0je](https://cloud.githubusercontent.com/assets/25574037/23246601/dd0badbc-f9cf-11e6-971d-0c54054d0687.png)

**Comment by a466350665** [comment]
删掉编译目录smart-sso-server，clear一下项目和tomcat，再看看mapper路径
![image](https://cloud.githubusercontent.com/assets/19278040/23246716/87266206-f9d0-11e6-817d-090a05c35b8a.png)

![image](https://cloud.githubusercontent.com/assets/19278040/23246698/6abecf22-f9d0-11e6-8fd1-eb4bd3e5baff.png)

**Comment by waitinguhere** [comment]
我使用的是idea。我重新导入一个项目，什么都没改。
![f0mw bt8x6up4c0rd5xmtl7](https://cloud.githubusercontent.com/assets/25574037/23247105/0d251fee-f9d3-11e6-8982-662d664b44ba.png)
![Uploading Q@R{80EK1(CD2[J79L6D%4D.png…]()

**Comment by waitinguhere** [comment]
![q r 80ek1 cd2 j79l6d 4d](https://cloud.githubusercontent.com/assets/25574037/23247116/21ac7836-f9d3-11e6-9ca6-f4506de634ea.png)

**Comment by a466350665** [comment]
把工程下的mapper文件夹，copy到编译路径下试试启动是否成功。如果OK了，就要自行查查编译问题了，idea环境我不熟悉

**Comment by waitinguhere** [comment]
好的，我到时候找个时间用myeclipse试试。谢谢你的耐心回答。
