### ISSUE TITLE
麻烦问下

### ISSUE THREAD

**Issue by wangan11** [a466350665/smart#5]
按照你的文档启动，访问任何请求都是404，少了什么，zookeeper也打开了

**Comment by a466350665** [comment]
服务启动有没有报错

**Comment by wangan88** [comment]
并没有,再研究下吧

**Comment by wangan88** [comment]
org.apache.ibatis.binding.BindingException: Invalid bound statement (not found): com.smart.sso.server.dao.UserDao.findByAccount ,配置文件我都看了都正确，不知道啥原因

**Comment by a466350665** [comment]
你容器是用的tomcat还是jetty，看一下smart-sso-server的编译目录下有没有对应的Mapper文件
![image](https://cloud.githubusercontent.com/assets/19278040/23537135/f7b97e4c-0004-11e7-96d5-a9c9ab60fd93.png)

**Comment by wangan88** [comment]
tomcat 确实没有

**Comment by a466350665** [comment]
是用的intellij idea？ 之前也有朋友遇到一样的问题   原因找到了自行查查看   我这里是eclipse

**Comment by wangan88** [comment]
对的idea,好的，谢谢了，项目不错

**Comment by wangan88** [comment]
<build>
				<resources>
					<resource>
						<directory>src/main/resources/env/dev</directory>
					</resource>
					<resource>
						<directory>src/main/java/com/smart/sso/server/mapper</directory>
						<targetPath>com/smart/sso/server/mapper</targetPath>
					</resource>
				</resources>
			</build> 这样就可以了

**Comment by wangan88** [comment]
那个两个sql文件，表中怎么没有密码呢，用户登录密码都没记录

**Comment by a466350665** [comment]
好的  密码在sql中是加密过的  明文文档里有
![image](https://cloud.githubusercontent.com/assets/19278040/23539135/00e09d5c-0014-11e7-8ab2-ea588a9585c8.png)

**Comment by wangan88** [comment]
![4 2_sydq9da 9tf5 o5438f](https://cloud.githubusercontent.com/assets/20237960/23540787/62f7844c-001e-11e7-81de-c5d6011bf247.png)

**Comment by wangan88** [comment]
没有admin啊

**Comment by wangan88** [comment]
我都没看到用户表中有admin

**Comment by wangan88** [comment]
是不是少插入了数据,我感觉是少了东西

**Comment by a466350665** [comment]
因为是单点登录，无论smart-demo-web还是smart-sso-server都是用的smart-sso库中的用户表（sys_user）
![image](https://cloud.githubusercontent.com/assets/19278040/23540898/02e61bbc-001f-11e7-9caa-5f94051da6c6.png)

**Comment by wangan88** [comment]
我错了，逗了，原来数据库有用户表，结果sql脚步出错了，没注意，谢谢
